import React, { useState } from "react";
import { ArrowRight, Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { Link } from "react-router-dom";
import { toast } from "react-hot-toast";
import { formatNaira, useCart } from "../context/CartContext";

function Cart() {
  const { items, updateQuantity, removeItem, applyCoupon, coupon, totals } = useCart();
  const [code, setCode] = useState("");
  const summary = totals("delivery");
  const submitCoupon = (event) => { event.preventDefault(); const result = applyCoupon(code); toast[result.ok ? "success" : "error"](result.message); if (result.ok) setCode(""); };
  if (!items.length) return <main className="mx-auto max-w-7xl px-4 py-24 text-center sm:px-6"><ShoppingBag className="mx-auto text-primary-500" size={52} /><h1 className="mt-5 font-heading text-3xl font-extrabold text-dark-950">Your cart is empty</h1><p className="mx-auto mt-3 max-w-md text-dark-500">Choose something delicious from the menu and it will stay here even after you refresh.</p><Link to="/menu" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-primary-500 px-6 py-3 font-bold text-white hover:bg-primary-600">Browse Menu <ArrowRight size={17} /></Link></main>;
  return <main className="bg-dark-50/50 py-10 sm:py-14"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div><p className="text-sm font-bold uppercase tracking-widest text-primary-500">Your order</p><h1 className="mt-2 font-heading text-3xl font-extrabold text-dark-950">Shopping Cart</h1><p className="mt-2 text-dark-500">Review your items before checkout.</p></div><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_380px]"><section className="space-y-4">{items.map((item) => <article key={item.id} className="flex gap-4 rounded-2xl border border-dark-100 bg-white p-4 shadow-soft">
    
    <img src={item.image} alt={item.name} className="h-24 w-24 rounded-xl object-cover" /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><h2 className="font-heading font-bold text-dark-950">{item.name}</h2><p className="mt-1 text-xs text-dark-500">{item.size?.name || "Regular"}{item.extras?.length ? ` · ${item.extras.map((extra) => extra.name).join(", ")}` : ""}</p></div><button onClick={() => removeItem(item.id)} className="text-dark-400 hover:text-danger" aria-label={`Remove ${item.name}`}><Trash2 size={17} /></button></div><div className="mt-4 flex items-center justify-between"><div className="flex items-center rounded-lg border border-dark-200"><button onClick={() => updateQuantity(item.id, item.quantity - 1)} className="p-2 text-dark-600 hover:text-primary-500"><Minus size={14} /></button><span className="min-w-8 text-center text-sm font-bold">{item.quantity}</span><button onClick={() => updateQuantity(item.id, item.quantity + 1)} className="p-2 text-dark-600 hover:text-primary-500"><Plus size={14} /></button></div><strong className="font-heading text-dark-950">{formatNaira(item.unitPrice * item.quantity)}</strong></div></div></article>)}</section><aside className="h-fit rounded-2xl border border-dark-100 bg-white p-5 shadow-soft sm:p-6"><h2 className="font-heading text-xl font-bold text-dark-950">Order Summary</h2><form onSubmit={submitCoupon} className="mt-5 flex gap-2"><input value={code} onChange={(event) => setCode(event.target.value)} placeholder="Coupon code" className="min-w-0 flex-1 rounded-xl border border-dark-200 px-3 py-3 text-sm outline-none focus:border-primary-500" /><button className="rounded-xl bg-dark-900 px-4 text-sm font-bold text-white">Apply</button></form>{coupon && <p className="mt-2 text-xs font-semibold text-success">{coupon.code} applied</p>}<div className="mt-6 space-y-3 border-t border-dark-100 pt-5 text-sm"><div className="flex justify-between text-dark-600"><span>Subtotal</span><span>{formatNaira(summary.subtotal)}</span></div>{summary.discount > 0 && <div className="flex justify-between text-success"><span>Discount</span><span>-{formatNaira(summary.discount)}</span></div>}<div className="flex justify-between text-dark-600"><span>Delivery</span><span>{formatNaira(summary.deliveryFee)}</span></div><div className="flex justify-between text-dark-600"><span>Tax</span><span>{formatNaira(summary.tax)}</span></div><div className="flex justify-between border-t border-dark-100 pt-4 text-base font-extrabold text-dark-950"><span>Total</span><span>{formatNaira(summary.total)}</span></div></div><Link to="/checkout" className="mt-6 flex items-center justify-center gap-2 rounded-xl bg-primary-500 px-5 py-3.5 text-sm font-bold text-white hover:bg-primary-600">Continue to Checkout <ArrowRight size={17} /></Link></aside></div></div>
    
    </main>;
}
export default Cart;
